### ISSUE TITLE
Install fails on EL 6 due to missing libselinux-python

### ISSUE THREAD

**Issue by paulmaunders** [Stouts/Stouts.nginx#5]
The role fails when run on Centos 6.x due to libselinux-python not being installed by default. 

TASK: [Stouts.nginx | Setup repo] ********************************************* 
failed: [default] => {"checksum": "39e5562257da539bf330df83d33879d3aa32ad67", "failed": true}
msg: Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

My suggestion would be to add this to the dependencies? I'll create a pull request with the necessary changes.

**Comment by klen** [comment]
Fixed in last release. Thank you for the report.
